{% set version = "0.8" %}

package:
  name: libfyaml
  version: {{ version }}

source:
  url: https://github.com/pantoniou/libfyaml/releases/download/v{{ version }}/libfyaml-{{ version }}.tar.gz
  sha256: dc4d4348eedca68e8e2394556d57f71410e7d61791a71cbe178302ebe5f26b99

build:
  number: 1
  skip: true  # [win]
  script:
    - ./bootstrap.sh
    - ./configure --prefix="${PREFIX}"
    - make
    - "[[ $CONDA_BUILD_CROSS_COMPILATION != '1' ]] && make check"
    - make install
  run_exports:
    - {{ pin_subpackage('libfyaml', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config

test:
  commands:
    - fy-tool -h

about:
  home: https://github.com/pantoniou/libfyaml
  summary: Fully feature complete YAML parser and emitter
  description: |
    A fancy 1.2 YAML and JSON parser/writer.

    Fully feature complete YAML parser and emitter, supporting the latest
    YAML spec and passing the full YAML testsuite.

    It is designed to be very efficient, avoiding copies of data, and
    has no artificial limits like the 1024 character limit for implicit keys.

    libfyaml is using <https://github.com/yaml/yaml-test-suite>
    as a core part of it's testsuite.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pantoniou.github.io/libfyaml
  dev_url: https://github.com/pantoniou/libfyaml

extra:
  recipe-maintainers:
    - MarDiehl
